name: Django testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Coverage report
      run: |
        pip install coverage
        coverage run manage.py test
        coverage report
    - name: Django testing
      run: |
        python manage.py test
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: 162.241.71.29
        username: root
        password: Mithu@123
        REMOTE_DIR: /root/yelhoumee/YelhoumeeNewPro
        protocol: ftps
        port: 22

#    - name: Deploy to VPN Server
#      uses: Techie-Pi/node-vps-deployment@main
#      with:
#        remote-path: "root/yelhoumee/YelhoumeeNewPro/action/"
#        host: 162.241.71.29
#        username: "root"
#        port: 22
##        password: ${{ secrets.staging-password }}
#        password: Mithu@123
#        pm2-id: "staging"
